In [70]:
import torch

In [71]:
torch.manual_seed(7)
features = torch.randn(1,3)
print (features)

tensor([[-0.1468,  0.7861,  0.9468]])


In [72]:
n_input=features.shape[1]
print (n_input)

3


In [73]:
n_hidden = 2
n_output = 1

In [74]:
torch.manual_seed(7)
features = torch.randn(1,3)
print (features)
n_input=features.shape[1]
print (n_input)
weights_input_hidden = torch.randn(n_input,n_hidden)
print (weights_input_hidden)
weights_hidden_out = torch.randn(n_hidden,n_output)
print (weights_hidden_out)
bias_input_hidden = torch.randn(1,n_hidden)
print (bias_input_hidden)
bias_hidden_out = torch.randn(1, n_output)

tensor([[-0.1468,  0.7861,  0.9468]])
3
tensor([[-1.1143,  1.6908],
        [-0.8948, -0.3556],
        [ 1.2324,  0.1382]])
tensor([[-1.6822],
        [ 0.3177]])
tensor([[0.1328, 0.1373]])


In [75]:
def activation(x):
    return 1/(1+torch.exp(-x))

In [76]:
h = activation(torch.mm(features, weights_input_hidden) + bias_input_hidden)
output = activation(torch.mm(h, weights_hidden_out) + bias_hidden_out)
print(output)

tensor([[0.3171]])


In [77]:
first = activation(torch.mm(features, weights_input_hidden)+bias_input_hidden)

In [78]:
print (first)

tensor([[0.6813, 0.4355]])


In [79]:
second =activation(torch.mm(first, weights_hidden_out) + bias_hidden_out
                  )

In [80]:
print (second)

tensor([[0.3171]])
