In [30]:
import torch


In [31]:
def activation(x):
    return (1/(1+torch.exp(-x)))

In [32]:
torch.manual_seed(7)
features=torch.randn(1,5)
weights=torch.randn_like(features)
bias= torch.randn(1,1)

In [33]:
print (features)
print (weights)
print (bias)

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
tensor([[0.3177]])


In [34]:
y = activation((features*weights).sum() + bias)

In [35]:
print (y)

tensor([[0.1595]])


In [36]:
print (weights.shape)


torch.Size([1, 5])


In [37]:
print (features.shape)

torch.Size([1, 5])


In [38]:
weights_reshaped = weights.view(5,1)
print (weights_reshaped.shape)

torch.Size([5, 1])


In [39]:
print (weights.shape)


torch.Size([1, 5])


In [40]:
y = activation(torch.mm(features, weights_reshaped) + bias)

In [41]:
print (y)


tensor([[0.1595]])
